name: Development build

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios
    
    runs-on: macos-latest   # runner cloud gratuit
    
    steps:
      - name: Remove work folders
        run: |
          echo "before"
          ls -lah ./ 
          rm -rf ./* || true
          rm -rf ./.??* || true
          echo "after"
          ls -lah ./
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout repository submodules
        run: git submodule update --init --recursive

      - name: Install gmake
        run: |
          brew install make
          ln -s $(which make) /usr/local/bin/gmake   # create gmake alias

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: |
          echo "sha=$(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*')" >> $GITHUB_OUTPUT

      # cache / build gl4es steps skipped as in your workflow
      # ...

      - name: Build for ${{ matrix.platform_name }}
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export SLIMMED=1
          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          elif [ "${{ matrix.platform_name }}" == "tvos" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          else
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          fi

      - name: Upload regular ipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload slimmed ipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}.ipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}.ipa

      - name: Upload slimmed tipa
        uses: actions/upload-artifact@v3
        with:
          name: org.angelauramc.amethyst.slimmed-${{ matrix.platform_name }}-trollstore.tipa
          path: artifacts/org.angelauramc.amethyst.slimmed-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload PojavLauncher.dSYM
        if: matrix.platform_name == 'ios'
        uses: actions/upload-artifact@v3
        with:
          name: AngelAuraAmethyst.dSYM
          path: artifacts/AngelAuraAmethyst.dSYM
